version: "3.8"
services:
  database:
    container_name: roommate_postgres
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: secret